name: Commit automático diario

on:
  schedule:
    - cron: '0 12 * * *'  # Todos los días a las 7am Colombia (UTC-5)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Agregar línea con la fecha
        run: |
          echo "Contribución del día: $(date)" >> log.txt

      - name: Hacer commit y push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Zentheriun"
          git config user.email "Zentheriun@gmail.com"
          git pull origin main --rebase || true
          git add log.txt
          git commit -m "✅ Commit automático diario" || echo "Nada para commitear"
          git push https://x-access-token:${TOKEN}@github.com/Zentheriun/Contributions.git HEAD:main
